workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m1 # استخدم أحدث الأجهزة المتاحة لأداء أفضل
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Build iOS application
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
