workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      - name: 🔹 Pre-build setup
        script: |
          flutter clean
          flutter pub get
          flutter precache

      - name: 🔹 Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # ✅ اختياري: ممكن تعمل build للـ simulator لو محتاج تجهز podhelper
      # - name: Build for simulator
      #   script: flutter build ios --simulator

      - name: 🔹 Build iOS App (no code sign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app
