workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      # 🔹 Pre-build setup
      - name: Pre-build setup
        script: |
          flutter clean
          flutter pub get
          flutter precache
          flutter build ios --simulator

      # 🔹 Install CocoaPods after generating podhelper.rb
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 🔹 Build iOS (no code sign)
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app
