workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      # 1. تنظيف المشروع
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      # 2. تنظيف وإعادة تثبيت الـ Pods
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod install --repo-update
          cd ..

      # 3. بناء iOS بدون توقيع
      - name: Build iOS
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
