workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods

    scripts:
      # 1️⃣ تنظيف المشروع وتحميل الباكجات
      - name: 🔹 Pre-build setup
        script: |
          flutter clean
          flutter pub get
          flutter precache

      # 2️⃣ تجهيز Podfile أوتوماتيك لو ناقص
      - name: 🔹 Ensure Podfile exists
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            echo "Podfile not found. Creating a default Podfile..."
            cat <<EOF > Podfile
            platform :ios, '12.0'
            use_frameworks!
            use_modular_headers!

            target 'Runner' do
              flutter_application_path = '../'
              eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
            end
          EOF
          fi
          cd ..

# 3️⃣ تثبيت الـ CocoaPods بعد تنظيف القديم
      - name: 🔹 Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # 4️⃣ بناء التطبيق iOS (Release بدون توقيع كود)
      - name: 🔹 Build iOS App (no code sign)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app
