workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods

    scripts:
      - name: 🔹 Clean & Get Dependencies
        script: |
          flutter clean
          flutter pub get

      - name: 🔹 Regenerate Podfile and Install Pods
        script: |
          rm -f ios/Podfile
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: 🔹 Build iOS App (No Code Sign)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app

