# yaml-language-server: $schema=https://json.schemastore.org/codemagic.yaml

workflows:
  ios-build-workflow:
    name: iOS Build Workflow

    # 1. THIS IS THE MOST IMPORTANT FIX: Use a modern build machine.
    # This ensures you get up-to-date versions of macOS, Xcode, and CocoaPods.
    instance_type: mac_mini_m2 # or mac_mini_m1

    # 2. Specify the latest stable software versions.
    environment:
      flutter: stable     # Use the latest stable Flutter version
      xcode: latest       # Use the latest Xcode version
      cocoapods: default  # Let Codemagic pick the version compatible with Xcode

    # 3. Define the build scripts in the correct order.
    scripts:
      - name: 1. Clean Flutter project
        script: |
          set -e # Exit immediately if a command fails
          flutter clean

      - name: 2. Get Flutter packages
        script: |
          set -e
          flutter pub get

      - name: 3. Clean and update CocoaPods
        script: |
          set -e
          cd ios
          # This ensures a clean installation of pods
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: 4. Build iOS application
        script: |
          set -e
          # Use --release for App Store builds or --debug for testing
          flutter build ios --release --no-codesign

    # 4. Specify the output artifacts.
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
