workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      # تنظيف المشروع قبل البناء
      - name: Clean Project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      # تثبيت باكجات Dart
      - name: Get Flutter Packages
        script: flutter pub get

      # تثبيت Pods
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # بناء iOS (بدون توقيع كود)
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app
