workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods

    scripts:
      - name: 🔹 Clean & Get Dependencies
        script: |
          flutter clean
          flutter pub get
          flutter precache

      - name: 🔹 Re-generate Podfile
        script: |
          cd ios
          rm -rf Podfile Podfile.lock Pods
          flutter pub get
          flutter precache
          pod init
          # إعادة إنشاء Podfile من flutter podhelper
          echo "platform :ios, '12.0'" > Podfile
          echo "use_frameworks!" >> Podfile
          echo "use_modular_headers!" >> Podfile
          echo "" >> Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  flutter_application_path = '../'" >> Podfile
          echo "  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)" >> Podfile
          echo "end" >> Podfile
          pod install --repo-update
          cd ..

      - name: 🔹 Build iOS App (No Code Sign)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app
