platform :ios, '13.0'

use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path('..', __dir__)
eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')))
flutter_root = `flutter --version --machine`.match(/"flutterRoot":"([^"]+)"/)[1]
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  flutter_ios_podfile_setup
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
