platform :ios, '14.0'

use_frameworks! :linkage => :static
use_modular_headers!

flutter_application_path = File.expand_path('..', __dir__)
# المسار الصحيح للـ podhelper
flutter_root = `which flutter`.strip
flutter_root = File.expand_path("../..", flutter_root)

flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_ios_podfile_setup

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
