name: Flutter Multi-Platform Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Upgrade Flutter and Dart
        run: |
          flutter upgrade
          flutter doctor

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter clean & get packages
        run: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods and setup iOS dependencies
        run: |
          sudo gem install cocoapods
          cd ios
          rm -f Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Create iOS Archive
        run: |
          mkdir -p build/ios/ipa
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/
          cd build/ios/ipa
          zip -r Runner.ipa Runner.app
          cd ../../..

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/ios/ipa/*.ipa

  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Upgrade Flutter and Dart
        run: |
          flutter upgrade
          flutter doctor

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter clean & get packages
        run: |
          flutter clean
          flutter pub get

      - name: Build Android APK Release
        run: flutter build apk --release

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/*.apk

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Upgrade Flutter and Dart
        run: |
          flutter upgrade
          flutter doctor

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter clean & get packages
        run: |
          flutter clean
          flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows Executable
        run: flutter build windows --release

      - name: Create Windows Archive
        run: |
          cd build/windows/x64/runner/Release
          7z a -tzip ../../../../../windows-release.zip *
          cd ../../../../../

      - name: Upload Windows Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-exe
          path: windows-release.zip

